### ISSUE TITLE
require 'SSD1306' fails

### ISSUE THREAD

**Issue by Jkillelea** [zeiv/SSD1306-ruby#1]
Running this on my raspberry pi with ruby 2.1.5p273 and the gems:
i2c (0.4.0)
rmagick (2.15.4)
SSD1306 (0.5.1)

Fails at runtime on line 1.

`/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file --``SSD1306 (LoadError)`
    `from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in 'require'`
    `from displaytest.rb:1:in <main>`

**Comment by Jkillelea** [comment]
requiring from a relative path - `require './SSD1306-ruby/lib/SSD1306.rb'` - also fails, so I'm assuming this is a ruby error, not a library specific one.
